### ISSUE TITLE
Finish `ssh` feature

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Linux-Auto-Customizer#105]
I was checking the Customizer and I found the feature `ssh` which seeems unfinished or without a clear purpose. 

Can you finish it or delete it if it is garbage?

I do maintain the feature `opensshServer`, but I do not know anything about this feature.

**Comment by Axlfc** [comment]
This feature relies in the existence of _nemo-connect-server_. When the feature nemo is already installed and ssh is being installed, a desktop shortcut named "Connect to Server" should be created in the desktop because is a GUI for ssh connections.

**Comment by Axlfc** [comment]
De per se, ssh client is an apt-get install feature.

**Comment by Axlfc** [comment]
The **expected** behavior of **ssh** installation, was to create a desktop shortcut named "Connect to Server" that opens a visual GUI to make server connections if _nemo_ was installed. Due to _nemo-connect-server_ binary does not have arguments, the strategy was to enter in a regular ssh connection (IP, Port (22 is default so if no port given default value is used), username, password) and then, open nemo in that folder in the local client. _'o function'_, after the installation of ssh (If the remote system server has X11 forwading enabled and Nemo installed, you could tunnel X through ssh and display a remote instance of Nemo on your local machine, which might then allow sudo elevated permissions) then would be using the following command to be able to connect to a remote server and see a GUI.

<code>ssh -X</code>

**Comment by AleixMT** [comment]
> The **expected** behavior of **ssh** installation, was to create a desktop shortcut named "Connect to Server" that opens a visual GUI to make server connections if _nemo_ was installed. Due to _nemo-connect-server_ binary does not have arguments, the strategy was to enter in a regular ssh connection (IP, Port (22 is default so if no port given default value is used), username, password) and then, open nemo in that folder in the local client. _'o function'_, after the installation of ssh (If the remote system server has X11 forwading enabled and Nemo installed, you could tunnel X through ssh and display a remote instance of Nemo on your local machine, which might then allow sudo elevated permissions) then would be using the following command to be able to connect to a remote server and see a GUI.
> 
> `ssh -X`

No, you are full of crap. 

Just create a desktop launcher for `nemo-connect-server` and raise PR.

**Comment by Axlfc** [comment]
<code>ssh -X</code> will let us run installed graphic applications of the server in our host.

**Comment by AleixMT** [comment]
> No, you are full of crap.
> 
> Just create a desktop launcher for nemo-connect-server and raise PR.

Could you please do this and solve this issue?
