### ISSUE TITLE
stableDiffusion feature - Python3 virtual environment installation

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#107]
I want to install Stable Diffusion but it seems the python3 virtual environment is no properly functioning.

I add here the log:
[URL to the log](https://pastebin.com/1Vmiy7sJ)

Everything related to python3-venv is not being created, so when I open the web-ui desktop shortcut it opens and close the server terminal and program does not start.

This problem seems to be exclusively related to the web-ui GPU version, the CLI commands are  working as expected.

Current Python3 version: 3.10.6
Ubuntu version: 22.04.2 LTS (_Jammy Jellyfish_)

I can't install python3.8 with the command <code>sudo apt-get install -y python3.8</code> it says the package «python3.8» has no installation candidate.

**Comment by AleixMT** [comment]
> Everything related to python3-venv is not being created,

The updated logs show that everything is being created. I do not see any error. The environment is properly functioning. 

> I can't install python3.8 with the command sudo apt-get install -y python3.8 it says the package «python3.8» has no installation candidate.

Obviously you can not install Python 3.8 if your current version is 3.10 as you stated in the previous sentence... :disappointed: 

If you have an error they will be probably on the feature side. I do not see anything unexpected from the core side. Also check that there are warnings on your installation. This will impact the stability of the installation of your feature.

I am closing this issue since I do see that the env is properly created. Reopen it if you have further inquiries.
