### ISSUE TITLE
End to add features

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#19]
- [x] #106
- [ ]  krita (with stableDiffusion)
- [ ]  vncserver
- [ ]  houdini sideFX
- [ ]  python3 uninstall BUG (ln -s python python3 related)
- [x]  notflix (without subtitles extension)

**Comment by AleixMT** [comment]
# **Notice that in the end of 2023 all the unmerged features will be removed from the git tree by deleting the dangling branches on server side (aproximately one year).** 

Please, enhance code quality, style, commentaries, documentation, readability, understandibility and traceability of the code of these features. Also, simplify and divide content of bigger features, specially stableDiffusion. There must not be any unused code or configuration that its purpose is not clear. Currently, features are very far from being apt to customizer standards and as thus they can not be merged into `develop` branch. 

#### **This is the issue with the most priority wight now, before any other one that you have assigned.** 

When the previous requirements are ensured on one of the mentioned features, raise a PR and I will review the code and request further changes to ensure customizer standards if needed.

**Comment by AleixMT** [comment]
Can you do notflix first? I think that is not going to be that difficult to finish... But if the automatic addition of the subtitles does not work just remove that code and leave the functional and working code. Focus on finishing a feature with a basic functionality instead of increasing its complexity and capacities until the point that you no longer know how to proceed to make it work. 

I strongly recommend you that you follow the [KISS](https://en.wikipedia.org/wiki/KISS_principle) principle.

**Comment by AleixMT** [comment]
Also, open a single PR for each feature that you want to merge into `develop`. Start with notflix

**Comment by AleixMT** [comment]
@Axlfc  Add markdown documentation to notflix feature, it is missing

**Comment by Axlfc** [comment]
> @Axlfc Add markdown documentation to notflix feature, it is missing

PR #91 Review required

**Comment by AleixMT** [comment]
Split this issue into many issues, one for each individual feature. 

I am closing it as won't fix.
