### ISSUE TITLE
add github for pages

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#47]
Include #35

**Comment by Axlfc** [comment]
We will be using Jekyll and Github for pages to mantain our web server

**Comment by Axlfc** [comment]
[Link to current page](https://autocustomizer.github.io/) This is very Basic.

[Repository page](https://github.com/AutoCustomizer/autocustomizer.github.io)

[Set up github pages site with jekyll; how to test](https://docs.github.com/es/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll)

[Trouble creating new Jekyll site](https://stackoverflow.com/questions/61704004/trouble-creating-a-new-jekyll-site-could-not-locate-gemfile-or-bundle-direct)

**Comment by Axlfc** [comment]
A good starting point would be to search and choose a good suited jekyll theme for the webpage design and then set it up in the repository.

The following webpages have different Jekyll themes:

- [jekyllthemes](http://jekyllthemes.org/)
- [jamstackthemes](https://jamstackthemes.dev/ssg/jekyll/)
- [jekyllrb](https://jekyllrb.com/docs/themes/)
- [jekyllthemes](https://jekyllthemes.io/)

How to add jekyll theme:

- [dev-yakuza](https://dev-yakuza.posstree.com/en/jekyll/theme/)
- [docs.github](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll)

**Comment by AleixMT** [comment]
Ok, seems fine to me, but use this organization: [https://github.com/Gua-tk](https://github.com/Gua-tk)

**Comment by Axlfc** [comment]
For that organization, give proper user access and create a new repostory on the profile with the name: _gua-tk.github.io_

To mantain a Github 4 Pages site, the dev team need to have editing rights to the following repo (right now it does not exist):
https://github.com/Guat-tk/guat-tk.github.io

**Comment by AleixMT** [comment]
Ok, now you have privileges to do so

**Comment by Axlfc** [comment]
New webpage pointing to [https://gua-tk.github.io](https://gua-tk.github.io)

Very very basic.

Need to apply new theme and organize and design some content to show on the page.

All changes in repo https://github.com/Gua-tk/gua-tk.github.io will be shown in the webpage after Github For Pages actions finish server files upload.

For local testing (to be able to work without making dirty push to server), use this link as reference: [Testing Github for Pages Site Locally With Jekyll](https://docs.github.com/es/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll)

- Install [Jekyll](https://jekyllrb.com/docs/installation/)
- Install [Bundler](https://bundler.io/)

Use the following command within the repo's cloned folder to start a local server for testing the webpage and its changes with the command:

<code> bundle exec jekyll serve </code>

**Comment by AleixMT** [comment]
First design the page and think before hand what are you going to put in it and why. Then implement

**Comment by Axlfc** [comment]
Implemented this [web page Jekyll theme](https://github.com/Remyie/remy) in [web repo](https://github.com/Gua-tk/gua-tk.github.io)

**Comment by Axlfc** [comment]
The web page should include the next sections to explain the organization and the programs we are developing as a team.

1. **About Us**: This section should provide a brief overview of the organization, its mission, and its goals. It should also include information about the two developers and the program, Customizer.

2. **Features**: This section should provide a detailed description of the features of Linux-Auto-Customizer, such as the ability to automate unattended installations of +250 programs, and the phone app  ScriptsStudio to manage those installations with ease.

3. **Documentation**: This section should provide detailed documentation on how to use the program, as well as any other relevant information about the program.

4. **Support**: This section should provide contact information for the developers, as well as a forum or other support channels for users to get help with their issues.

5. **News/Blog**: This section should provide news and updates about the program, such as new features, bug fixes, and other relevant information.

6. **Downloads**: This section should provide links to download the program and its associated files. Example: Last Customizer release.

7. **Social Media**: This section should provide links to the organization's social media accounts, such as Twitter, Github, Buymeacoffe...

**Comment by AleixMT** [comment]
Ok, this seems fine. 

Though, notice that you have some dependencies to other issues: #31, #32, #33, #35.

You can start with the page first, but there are things that is convenient that you do before, like #33. 

Anyway, you need to think how to organize all the information that you have without repeating yourself and considering some aspects of our projects:
- Features (2). Do not write a single word about Scripts Studio until you have made your first modification to the algorithm and have it compiling and running. Until then Scripts Studio is not considered part of the project since _de facto_ none of us know how to make that piece of software work. 
- Features (2): What is the difference between this section and the documentation? 
- Documentation section (3). What is the difference between the documentation in the wiki, the documentation in the page and the documentation in the `README.md`? You need to **THINK** about those aspects before actually designing the page. Meta project issues involve a general view of the project. These are the important aspects of designing, and as such the ones that you need to state. Designing is not **only** writing an index. 
- Support section (4). What is the purpose of having to implement a forum when you have a free service like github issues that provide exactly this functionality? Do I really need to state this OBVIOUS thing? This is nonsense!

**Comment by AleixMT** [comment]
Why did you remove your asssignment? @Axlfc

**Comment by AleixMT** [comment]
are you going to finish this issue?

**Comment by AleixMT** [comment]
Since you are not addressing the requested changes I will be deleting the template that you copied for the wiki. This is exactly what we did not need.
